server.port=${SERVER_PORT:8085}

keycloak.server-url=${KEYCLOAK_SERVER_URL:http://localhost:8081}
keycloak.realm=${KEYCLOAK_REALM:payment-system}
keycloak.client-id=${KEYCLOAK_CLIENT_ID:authentication-service}
keycloak.client-secret=${KEYCLOAK_CLIENT_SECRET:test-secret}

services.user-service.url=${SERVICES_USER_SERVICE_URL:http://localhost:8082}

keycloak.admin.username=${KEYCLOAK_ADMIN_USERNAME:admin}
keycloak.admin.password=${KEYCLOAK_ADMIN_PASSWORD:admin}

spring.security.oauth2.resourceserver.jwt.issuer-uri=${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:http://localhost:8081/realms/payment-system}